- name: Ping server
  ansible.builtin.ping:

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install gnupg, apt-transport-https, java
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https
      - openjdk-8-jdk
    state: present

- name: Copying the deb package to the host
  ansible.builtin.copy:
    src: files/kibana-7.17.0-amd64.deb
    dest: /tmp/kibana-7.17.0-amd64.deb

- name: Installing the deb package
  ansible.builtin.apt:
    deb: /tmp/kibana-7.17.0-amd64.deb
    state: present

- name: Configure Kibana to connect to Elasticsearch
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml

- name: Start and enable Kibana service
  ansible.builtin.service:
    name: kibana
    state: started
    enabled: yes